-- Eventos web para analitica tipo Vercel (retencion recomendada: 90 dias)

create table if not exists public.web_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  session_id text,
  page_path text,
  page_url text,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  country text,
  region text,
  city text,
  device_type text,
  browser text,
  ip_hash text,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists web_events_created_at_idx on public.web_events (created_at desc);
create index if not exists web_events_event_name_idx on public.web_events (event_name);
create index if not exists web_events_page_path_idx on public.web_events (page_path);
create index if not exists web_events_session_id_idx on public.web_events (session_id);
create index if not exists web_events_referrer_host_idx on public.web_events (referrer_host);
create index if not exists web_events_country_idx on public.web_events (country);
create index if not exists web_events_utm_source_idx on public.web_events (utm_source);
create index if not exists web_events_utm_campaign_idx on public.web_events (utm_campaign);

create or replace function public.cleanup_web_events_90d()
returns bigint
language plpgsql
as $$
declare
  deleted_count bigint;
begin
  delete from public.web_events
  where created_at < now() - interval '90 days';

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- Opcional: programar esta limpieza diaria con pg_cron
-- select cron.schedule('cleanup_web_events_90d_daily', '30 3 * * *', $$select public.cleanup_web_events_90d();$$);
